apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: terraform-pipeline-vm-crif
  namespace: gitops-tekton
spec:
  tasks:
    - name: github-app-token
      params:
        - name: installation_id
          value: "41977302"
        - name: application_id
          value: "392248"
      taskRef:
        kind: Task
        name: github-app-token-vm-crif
      workspaces:
        - name: secrets
          workspace: github-secret
    - name: git-clone
      params:
        - name: url
          value: "https://x-access-token:$(tasks.github-app-token.results.token)@github.com/neenspa/vm-crif.git"
      taskRef:
        kind: ClusterTask
        name: git-clone
      runAfter:
        - github-app-token
      workspaces:
        - name: output
          workspace: terraform-files
    - name: terraform-vm-crif
      taskRef:
        kind: Task
        name: terraform-vm-crif
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: terraform-files
        - name: terraform-variables
          workspace: terraform-variables
  workspaces:
    - name: terraform-files
    - name: github-secret
    - name: terraform-variables
